ENQUADRAMENTO = '01100111'
MSG_INICIO = 0
MSG_ORIGEM = 1
MSG_DESTINO = 2
MSG_RECEBIDA = 3
MSG_LIDA = 4
MSG_TIPO = 5
MSG_DADOS = 6
MSG_PARIDADE = 7

PASSAGEM_BASTAO = 0
FAZ_APOSTA = 1
FAZ_JOGADA = 2
ENVIA_RESULTADOS = 3
ATUALIZA_FICHAS = 4
VERIFICA_GANHADOR = 5
ANUNCIA_GANHADOR = 6